"""
process_sheet2.py — Populate Sheet 3 from transactions pasted in Sheet 2.

Usage
-----
  python process_sheet2.py [OUTPUT_XLSX]

  OUTPUT_XLSX   Path to the workbook produced by main.py.
                Default: output.xlsx

Run this AFTER you have pasted Bank Hapoalim transactions into Sheet 2
("בנק") starting at row 6 (columns A–I) and saved the file.

The script:
  1. Reads all rows from Sheet 2 starting at row 6.
  2. Keeps only rows where the balance column (I) is negative.
  3. Rewrites Sheet 3 ("חישוב החזר לפי יתרות בבנק") with those rows,
     day-count formulas (J, K) and the interest formula (L).
  4. Saves the file in-place.

Sheet 3 header (rows 1-6, rates, account info) and the anchor date in
row 7 are preserved exactly as generated by main.py.
"""

from __future__ import annotations

import logging
import sys
from datetime import datetime
from typing import Optional

import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ── Minimal style helpers (self-contained — no dependency on excel_writer) ───

def _font(bold: bool = False, size: float = 11) -> Font:
    return Font(bold=bold, size=size, name="Arial")


def _fill(hex_rgb: str) -> PatternFill:
    return PatternFill(fill_type="solid", fgColor=hex_rgb)


def _rtl(horizontal: str = "general") -> Alignment:
    return Alignment(horizontal=horizontal, vertical="bottom", readingOrder=2)


def _set(ws, ref: str, value, *, bold: bool = False,
         number_format: Optional[str] = None,
         fill_hex: Optional[str] = None,
         alignment: Optional[Alignment] = None) -> None:
    cell = ws[ref]
    cell.value = value
    cell.font = _font(bold=bold)
    if number_format:
        cell.number_format = number_format
    if fill_hex:
        cell.fill = _fill(fill_hex)
    if alignment:
        cell.alignment = alignment


# ── Helpers ───────────────────────────────────────────────────────────────────

def _parse_date(val) -> Optional[datetime]:
    if isinstance(val, datetime):
        return val
    if isinstance(val, str):
        for fmt in ("%d.%m.%Y", "%d.%m.%y", "%d/%m/%Y", "%d/%m/%y"):
            try:
                return datetime.strptime(val.strip(), fmt)
            except ValueError:
                pass
    return None


def _to_float(val) -> Optional[float]:
    if val is None:
        return None
    if isinstance(val, (int, float)):
        return float(val)
    try:
        return float(str(val).strip().replace(",", ""))
    except ValueError:
        return None


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else "output.xlsx"
    logger.info("Opening: %s", path)

    # Open once — data_only=False lets us read static values AND write formulas.
    # (Static cells like L2, L3, A7, and the charged amount are plain numbers/
    #  dates, so they read fine without data_only=True.)
    wb = openpyxl.load_workbook(path, data_only=False)

    try:
        ws2 = wb["בנק"]
    except KeyError:
        logger.error("Sheet 'בנק' not found in %s", path)
        return 1

    try:
        ws3 = wb["חישוב החזר לפי יתרות בבנק"]
    except KeyError:
        logger.error("Sheet 'חישוב החזר לפי יתרות בבנק' not found in %s", path)
        return 1

    # ── Read Sheet 2 transactions (row 6 onwards) ─────────────────────────────
    # Layout: A=date, B=code, C=operation, D=details, E=reference,
    #         F=batch, G=debit, H=credit, I=balance
    transactions = []
    for row in ws2.iter_rows(min_row=6, values_only=True):
        if all(c is None for c in row):
            continue
        date_val = row[0] if len(row) > 0 else None
        if date_val is None:
            continue
        balance = _to_float(row[8]) if len(row) > 8 else None
        transactions.append({
            "date":      date_val,
            "code":      row[1] if len(row) > 1 else "",
            "operation": row[2] if len(row) > 2 else "",
            "details":   row[3] if len(row) > 3 else "",
            "reference": row[4] if len(row) > 4 else "",
            "batch":     row[5] if len(row) > 5 else "",
            "debit":     _to_float(row[6]) if len(row) > 6 else None,
            "credit":    _to_float(row[7]) if len(row) > 7 else None,
            "balance":   balance,
        })

    # ── Determine period_to from Sheet 3 header (A5 contains the account/period line) ──
    period_to_dt = None
    header_cell = ws3["A5"].value or ""
    import re as _re
    m = _re.search(r"(\d{2}/\d{2}/\d{2,4})\s*$", str(header_cell))
    if m:
        for _fmt in ("%d/%m/%y", "%d/%m/%Y"):
            try:
                period_to_dt = datetime.strptime(m.group(1), _fmt).date()
                break
            except ValueError:
                pass
    if period_to_dt:
        logger.info("period_to: %s", period_to_dt)
    else:
        logger.warning("Could not parse period_to from Sheet 3 A5 — all dates will be included")

    # Filter: first transaction per date, exclude dates after period_to.
    # Matches the boss's Sheet 3 logic exactly.
    from datetime import date as _date_type
    seen_dates: set = set()
    filtered_tx = []
    for tx in transactions:
        date_val = tx["date"]
        dt = _parse_date(date_val) if not isinstance(date_val, datetime) else date_val
        if dt is None:
            continue
        d = dt.date()
        if period_to_dt is not None and d > period_to_dt:
            continue
        if d in seen_dates:
            continue
        seen_dates.add(d)
        filtered_tx.append(tx)

    logger.info("Sheet 2: %d total rows → %d after first-per-date filter", len(transactions), len(filtered_tx))

    if not filtered_tx:
        logger.warning("No rows remain after filtering — Sheet 3 will have no data rows.")

    # ── Read parameters already written in Sheet 3 header ────────────────────
    anchor_date = ws3["A7"].value

    # Find Sheet 1's total_charged cell: scan column G for =SUM(G...:G...)
    sheet1_total_row = None
    try:
        ws1 = wb["פירוט ריבית חובה לפי PDF"]
        import re as _re2
        for cell in ws1["G"]:
            if isinstance(cell.value, str) and _re2.match(r"=SUM\(G\d+:G\d+\)", cell.value):
                sheet1_total_row = cell.row
                break
    except Exception:
        pass

    if sheet1_total_row:
        logger.info("Sheet 1 total_charged at G%d", sheet1_total_row)
    else:
        logger.warning("Could not locate total_charged in Sheet 1 — K{charged_row} will be 0")

    anchor_date = ws3["A7"].value
    logger.info("Anchor date: %s", anchor_date)

    # ── Clear existing data rows in Sheet 3 (rows 7 and below) ───────────────
    max_clear = max(ws3.max_row + 10, 8 + len(filtered_tx) + 20)
    for r in range(7, max_clear + 1):
        for c in range(1, 14):     # columns A–M
            ws3.cell(row=r, column=c).value = None

    # ── Re-write anchor date row 7 ────────────────────────────────────────────
    dt = _parse_date(anchor_date) if anchor_date is not None else None
    ws3["A7"].value        = dt if dt is not None else anchor_date
    ws3["A7"].number_format = "DD.MM.YYYY"
    ws3["A7"].alignment    = _rtl("center")

    # ── Write data rows ───────────────────────────────────────────────────────
    DATA_START    = 8
    num_fmt_money = "#,##0.00"
    YELLOW        = "FFFF00"

    for i, tx in enumerate(filtered_tx):
        n       = DATA_START + i
        is_last = (i == len(filtered_tx) - 1)

        dt = _parse_date(tx["date"])
        ws3[f"A{n}"].value        = dt if dt is not None else tx["date"]
        ws3[f"A{n}"].number_format = "DD.MM.YYYY"
        ws3[f"A{n}"].alignment    = _rtl("center")

        ws3[f"B{n}"].value     = tx["code"] or ""
        ws3[f"B{n}"].alignment = _rtl("center")
        ws3[f"C{n}"].value     = tx["operation"] or ""
        ws3[f"C{n}"].alignment = _rtl()
        ws3[f"D{n}"].value     = tx["details"] or ""
        ws3[f"D{n}"].alignment = _rtl()
        ws3[f"E{n}"].value     = tx["reference"] or ""
        ws3[f"E{n}"].alignment = _rtl("center")
        ws3[f"F{n}"].value     = tx["batch"] or ""
        ws3[f"F{n}"].alignment = _rtl("center")

        if tx["debit"] is not None:
            ws3[f"G{n}"].value        = tx["debit"]
            ws3[f"G{n}"].number_format = num_fmt_money
            ws3[f"G{n}"].alignment    = _rtl("right")
        if tx["credit"] is not None:
            ws3[f"H{n}"].value        = tx["credit"]
            ws3[f"H{n}"].number_format = num_fmt_money
            ws3[f"H{n}"].alignment    = _rtl("right")
        if tx["balance"] is not None:
            ws3[f"I{n}"].value        = tx["balance"]
            ws3[f"I{n}"].number_format = num_fmt_money
            ws3[f"I{n}"].alignment    = _rtl("right")

        # J: day count = previous row date − current row date.
        # Row 7 is the anchor (charge date), so J8 = A7-A8, J9 = A8-A9, etc.
        ws3[f"J{n}"].value        = f"=A{n-1}-A{n}"
        ws3[f"J{n}"].number_format = "0"
        ws3[f"J{n}"].alignment    = _rtl("center")

        # K: interest = effective_rate / 365 × balance × days
        ws3[f"K{n}"].value        = f'=IFERROR(($K$6/365*I{n}*J{n}),"")'
        ws3[f"K{n}"].number_format = num_fmt_money
        ws3[f"K{n}"].alignment    = _rtl("right")

    # ── Summary rows ──────────────────────────────────────────────────────────
    data_end    = DATA_START + len(filtered_tx) - 1 if filtered_tx else DATA_START - 1
    sum_row     = data_end + 1
    charged_row = sum_row + 1
    refund_row  = sum_row + 2

    ws3[f"K{sum_row}"].value        = f"=SUM(K{DATA_START}:K{data_end})" if filtered_tx else 0
    ws3[f"K{sum_row}"].number_format = num_fmt_money
    ws3[f"K{sum_row}"].font          = _font(bold=True)
    ws3[f"K{sum_row}"].alignment     = _rtl("right")
    ws3[f"L{sum_row}"].value         = "ריבית מחושבת"
    ws3[f"L{sum_row}"].font          = _font(bold=True)
    ws3[f"L{sum_row}"].alignment     = _rtl()

    if sheet1_total_row:
        s1_ref = f"'פירוט ריבית חובה לפי PDF'!G{sheet1_total_row}"
        ws3[f"K{charged_row}"].value = f"=-INT({s1_ref})"
    else:
        ws3[f"K{charged_row}"].value = 0
    ws3[f"K{charged_row}"].number_format = "#,##0"
    ws3[f"K{charged_row}"].alignment    = _rtl("right")
    ws3[f"L{charged_row}"].value        = "ריבית שירדה בפועל"
    ws3[f"L{charged_row}"].alignment    = _rtl()

    ws3[f"K{refund_row}"].value        = f"=K{sum_row}-K{charged_row}"
    ws3[f"K{refund_row}"].number_format = num_fmt_money
    ws3[f"K{refund_row}"].font          = _font(bold=True)
    ws3[f"K{refund_row}"].fill          = _fill(YELLOW)
    ws3[f"K{refund_row}"].alignment     = _rtl("right")
    ws3[f"L{refund_row}"].value         = "החזר"
    ws3[f"L{refund_row}"].font          = _font(bold=True)
    ws3[f"L{refund_row}"].fill          = _fill(YELLOW)
    ws3[f"L{refund_row}"].alignment     = _rtl()

    wb.save(path)
    logger.info("Done. Sheet 3 updated with %d rows. Saved: %s", len(filtered_tx), path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
